// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfh3yBJSR8sHMblLOB8rd0dk4_3R1lHpQ',
    appId: '1:55595611322:web:24b108fba03a7e534ebe83',
    messagingSenderId: '55595611322',
    projectId: 'mobilecomputing-1e5e2',
    authDomain: 'mobilecomputing-1e5e2.firebaseapp.com',
    storageBucket: 'mobilecomputing-1e5e2.appspot.com',
    measurementId: 'G-SZNGYMYS92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBenJ6Q9dEpisxdHC1PDbHmnwoEiELHSzs',
    appId: '1:55595611322:android:92c6b670d2d8554e4ebe83',
    messagingSenderId: '55595611322',
    projectId: 'mobilecomputing-1e5e2',
    storageBucket: 'mobilecomputing-1e5e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7kav3UblcTbTjoqO48xpD_TvSood_0KI',
    appId: '1:55595611322:ios:997355c8e94b24a94ebe83',
    messagingSenderId: '55595611322',
    projectId: 'mobilecomputing-1e5e2',
    storageBucket: 'mobilecomputing-1e5e2.appspot.com',
    iosBundleId: 'com.example.mobilecomputing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7kav3UblcTbTjoqO48xpD_TvSood_0KI',
    appId: '1:55595611322:ios:fedabb23bd90098d4ebe83',
    messagingSenderId: '55595611322',
    projectId: 'mobilecomputing-1e5e2',
    storageBucket: 'mobilecomputing-1e5e2.appspot.com',
    iosBundleId: 'com.example.mobilecomputing.RunnerTests',
  );
}
